version: "3.9"

services:
  fluorine:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: "postgres:alpine"
    ports: 
      - "5432:5432"
    env_file:
      - postgres.env
