name: Bug report
about: Create a report to help us improve
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Describe the issue in as much detail as possible
      placeholder: A clear and concise description of what the bug is. (you can add screenshots!)
      validations:
        required: true
  - type: textarea
    id: repro
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      validations:
        required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What's supposed to happen?
      placeholder: A clear and concise description of what you expected to happen.
      validations:
        required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add anything else important
      placeholder: Add any other context about the problem here.
      validations:
        required: false
