name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm

      - name: Install canvas tools to build from source # TODO: remove this once canvas releases a prebuild
        run: sudo apt install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm

      - name: Install canvas tools to build from source # TODO: remove this once canvas releases a prebuild
        run: sudo apt install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install dependencies
        run: npm ci

      - name: Register Problem Matcher
        run: echo "##[add-matcher].github/tsc.json"

      - name: Run TypeScript compiler
        run: npm run test:typescript
